swirl()
install.packages("swirl")
library(swirl)
install_from_swirl("Exploratory Data Analysis")
swirl()
head(pollution)
summary(pollution)
dim(pollution)
summary(pollution$pm25)
quantile(pollution)
quantile(pollution$pm25)
quantile(ppm)
boxplot(ppm)
boxplot(ppm, col="blue")
abline(h=12, col="blue")
abline(h=12)
hist(ppm,col="green")
rug(ppm)
r
hist(ppm,h=12,lwd=5)
low
high
hist(ppm,col="green" breaks=100)
hist(ppm,col="green", breaks=100)
rug(ppm)
hist(ppm,col="green")
abline(h=12,v=12,lwd=2)
abline(v=12,lwd=2)
abline(v=median(ppm),col="magenta,lwd=4")
abline(v=median(ppm),col="magenta",lwd=4)
head(pollution)
names(pollution)
table(pollution$region)
reg <- table(pollution$region)
reg
barplot(reg,col="wheat",main="Number of Counties in Each Region")
boxplot(pm25~region,data=pollution,col="red")
par(mrfrow=c(2,1),mar=c(4,4,2,1))
par(mfrow=c(2,1, mar = c(4,4,2,1))
botton
par(mfrow=c(2,1), mar = c(4,4,2,1))
subset
east <-subset(pollution, region=="east")
head(pollution)
head(east)
hist(east$pm25,col="green")
hist(east$pm25,col="green")
hist(subset(pollution,region=="west")$pm25,col="green")
latitude(ppm)
plot(pollution, )
with(pollution,plot(latitude,pm25))
abline(lwd=2,lty=2)
abline(h=12,lwd=2,lty=2)
plot(pollution$latitude,ool="pollution$region")
plot(pollution$latitude,ool=pollution$region)
plot(pollution$latitude,ppm,ool=pollution$region)
plot(pollution$latitude,ppm ,ool=pollution$region)
plot(pollution$latitude,ppm ,col=pollution$region)
abline(h=12,lwd=2,lty=2)
par(mfrow=c(1,2), mar=c(5,4,2,1))
west <-subset(pollution)
west <-subset(pollution,region=="west")
plot(west$latitude (x-axis),west$pm25(y-axis),title=west)
plot(west$latitude (x-axis),west$pm25(y-axis),title=west))
plot(west$latitude (x-axis),west$pm25(y-axis),title=west)
plot(west$latitude)
plot(west$latitude, west$pm25, main="west")
plot(west$latitude, west$pm25, main="Wst")
plot(west$latitude, west$pm25, main="West")
plot(east$latitude, east$pm25, main="East")
dev
e
dev.cur
?devices
?Devices
with(faithful,plot(eruptions,waiting))
title(main="Old Faithful Geyser data")
dev.cur()
pdf(file="myplot.pdf")
with(faithful,plot(eruptions,waiting))
title(main="Up arrow keys are great!")
title(main="Old Faithful Geyser data")
dev.cur()
dev.off()
dev.cur()
with(faithful,plot(eruptions,waiting))
title(main="Old Faithful Geyser data")
dev.cpy()
dev.copy()
dev.copy(png,png="geyserplot.png")
dev.copy(2,png="geyserplot.png")
dev.copy(png, file="geyserplot.png")
dev.off()
?Devices
with(faithful,plot(eruptions,waiting))
title(main="Old Faithful Geyser data")
dev.cur()
pdf(file="myplot.pdf")
title(main="Old Faithful Geyser data")
with(faithful,plot(eruptions,waiting))
title(main="Old Faithful Geyser data")
dev.cur()
dev.off()
dev.cur()
with(faithful,plot(eruptions,waiting))
title(main="Old Faithful Geyser data")
dev.copy(png, file="geyserplot.png")
dev.off()
head(cars)
with(cars)
with(cars,plot(speed,dist))
text(mean(cars$speed),max(cars$dist),"SWIRL rules!")
head()
head(cars)
head(state)
table(state$region)
xyplot(life.Exp,data=state,layout=c(4,1))
xyplot(lif,data=state,layout=c(4,1))
xyplot(life,data=state,layout=c(4,1))
xyplot(region,data=state,layout=c(4,1))
xyplot(state$region,data=state,layout=c(4,1))
xyplot(state$region,state,layout=c(4,1))
xyplot(state$region,state,c(4,1))
xyplot(cars,state,c(4,1))
xyplot(cars,state,layout=c(4,1))
xyplot(cars)
xyplot(state$region,state,)
xyplot(state$region,state)
xyplot(state$region,state,21)
xyplot(state,state,21)
info()
xyplot(state$Income,data=state,layout=c(4,1))
xyplot(state$Income,state,layout=c(4,1))
xyplot(state$Income~ Income | region
xyplot(Life.Exp ~ Income | region,state)
xyplot(Life.Exp ~ Income | region,state,layout=c(4,1))
xyplot(Life.Exp ~ Income | region,state,layout=c(2,2))
head(mpg)
dim(mpg)
table(mpg$model)
gplot(displ,hwy,mpg$variable)
ggplot2(displ,hwy,mpg$variable)
qplot(displ,hwy,mpg$variable)
qplot(displ,hy,mpg$variable)
qplot(displ,hwy,mpg)
qplot(mpg$variable,mpg$variable,mpg)
qplot(displ,hwy,data=mpg)
head(airquality)
range(ozone,na.rm set equal to TRUE)
range(airquality$Ozone,na.rm set equal to TRUE)
range(airquality$Ozone,rm set equal to TRUE)
range(airquality$Ozone,with(na.rm set equal to TRUE))
range(airquality$Ozone,with(airquality$Ozone.rm set equal to TRUE))
range(airquality$Ozone,na.rm set equal to TRUE)
range(airquality$Ozone,na.rm set equal to TRUE)
range(airquality$Ozone,na.rm set equal to TRUE)
range(Ozone,na.rm set equal to TRUE)
range(Ozone,(na.rm set equal to TRUE))
range(Ozone,(na.rm set))
range(Ozone,(na.rm ))
range(airquality$Ozone,(na.rm ))
range(airquality$Ozone,(airquality$Ozone ))
range(airquality$Ozone,na.rm=TRUE)
hist(airquality$Ozone)
table(airquality$Month)
boxplot(Ozone~Month,airquality)
boxplot(xlab="month",ylab="Ozone (ppb)",col.axis="blue")
boxplot(xlab="Month",ylab="Ozone (ppb)",col.axis="blue")
boxplot(Ozone~month,airquality,xlab="month",ylab="Ozone (ppb)",col.axis="blue")
boxplot(Ozone~Month,airquality,xlab="month",ylab="Ozone (ppb)",col.axis="blue")
boxplot(Ozone~Month,airquality,xlab="Month",ylab="Ozone (ppb)",col.axis="blue")
boxplot(Ozone~Month,airquality,xlab="Month",ylab="Ozone (ppb)",col.axis="blue",col.lab="red")
title(main="Ozone and Wind in New York City")
with(airquality,plot(airquality$Wind))
with(airquality,plot(Wind,Ozone))
title(main="Ozone and Wind in New York City")
length()
length(par())
names(par())
par()$pin
par()$fg
par("Pch")
par()$pch
par()$lty
plot(wind,Ozone,type="n")
plot(Wind,Ozone,type="n")
plot(airquality$Wind,airquality$Ozone,type="n")
title(main="Wind and Ozone in NYC")
apropriately <-subset(airquality.Month))
appropriately <-subset(airquality.Month))
appropriately <-subset(airquality.Month)
appropriately <-subset(airquality)
may <- subset(airquality, Month=5)
may <- subset(airquality, Month==5)
points(h=3,col="blue")
points(may,Ozone,col="blue")
points(may,airquality$Ozone,col="blue")
points(may,airquality$Ozone,h=3,col="blue")
points(airquality$Month,airquality$Ozone,h=3,col="blue")
points(may$Wind,may$Ozone,col="blue",pch=17)
notmay <- subset()
notmay <- subset(airquality,Month!=5)
points(notmay$Wind,notmay$Ozone,col="red",pch=5)
points(notmay$Wind,notmay$Ozone,col="red",pch=8)
legend(c(17,8),("blue","red"),("May","Other
legend(c(17,8),("blue","red"),("May","OtherMounts")
legend(c(17,8),("blue","red"),("May","OtherMounts"))
legend(c(17,8),("blue","red"),("May","OtherMonts"))
legend(c(17,8),("blue"),("red"),("May","OtherMonts"))
legend(c(17,8),("blue"),("red"),("May"),("OtherMonts"))
legend(c(),("blue"),("red"),("May"),("OtherMonts"))
legend(,("blue"),("red"),("May"),("OtherMonts"))
legend(("blue"),("red"),("May"),("OtherMonts"))
legend("topright",("blue"),("red"),("May"),("OtherMonts"))
legend("topright",("blue"),("red"),May,("OtherMonts"))
legend("topright")
legend("topright",("blue"))
legend("topright",pch=(17,8),col=("blue","red"),legend=c("May",Other Mounts"))
legend("topright",pch=c(17,8),col=("blue","red"),legend=c("May",Other Mounts"))
legend("topright",pch=c(17,8),col=c("blue","red"),legend=c("May",Other Mounts"))
legend("topright",pch=c(17,8),col=c("blue","red"),legend=c("May","Other Mounts"))
legend("topright",pch=c(17,8),col=c("blue","red"),legend=c("May","Other Monts"))
legend("topright",pch=c(17,8),col=c("blue","red"),legend=c("May","Other Months"))
dashed(lty=2,wd=2)
lty=2
abline(v=median(airquality$Wind),lty=2,lwd=2)
par(mfrow(c(1,2)))
par(mfrow(pch=c(1,2)))
par(mfrow(pch=c(1,2))mfrow(pch=c(1,2)))
par()$mfrow()
par()$mfrow(pch=c(1,2))
par()mfrow(pch=c(1,2))
mfrow
mfrow()
par(mfrow())
par()
 par(mfrow=c(1,2))
title(main="Ozone and Wind")
plot(airquality$Wind, airquality$Ozone, main = "Ozone and Wind")
plot(airquality$Ozone, airquality$Solar, main = "Ozone and Solar Radiation")
plot(airquality$Ozone, airquality$Solar.R, main = "Ozone and Solar Radiation")
par(mfrow = c(1, 3)
mar = c(4, 4, 2, 1)
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), oma =
| c(0, 0, 2, 0))
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), oma = c(0,0,2,0)
k
par(mfrow=c(1,3) mar= c(4,4,2,1), oma=c(0,0,2,0))
par(mfrow=c(1,3),mar= c(4,4,2,1), oma=c(0,0,2,0))
plot(airquality$Wind, airquality$Ozone, main="Ozone and wind")
plot(airquality$Wind, airquality$Ozone, main="Ozone and Wind")
plot(airquality$Solar.R, airquality$Ozone, main="Ozone and Solar Radiation")
plot(airquality$Temp, airquality$Ozone, main="Ozone and Temperature")
mtext("Ozone and Weather in New York City",outer=TRUE)
q()
getwd()
save.image("d:\\Documents\\Coursera\\w")
data<-read.table("household.txt",header = TRUE,sep = ";", stringsAsFactors = FALSE)
#converting the type of "Date" with as.date()
data$Date<-as.Date(data$Date,"%d/%m/%Y")
#Subsetting the data necessarys
dataed<-subset(data,Date >= "2007-02-01" & Date <= "2007-02-02") 
#converting the type of "Time"column from "character" to "Time with as.POSIXct()
dataed$Time<-as.POSIXct(paste(dataed$Date, dataed$Time), format="%Y-%m-%d %H:%M:%S")
#converting the rest of the columns into numeric with as.numeric()
dataed[,3:9]<-sapply(dataed[,3:9], as.numeric)
#Creating the PNG file
png(filename = "plot1.png")
with(hist(dataed$Global_active_data,xlab = "Global Active data(watts)",ylab = "Frequency",main = "Global Active data",col = "red"))
dev.off()
